### ISSUE TITLE
Bracket Pair Colorizer

### ISSUE THREAD

**Issue by vitaly-los** [junichi11/netbeans-php-enhancements#17]
Hello, first of all thank you for  your great plugins, that very useful for php developers.
And I just want to ask, what about add this features to php-enhancements plugin
On visual studio it's one of most popular extensions - 

> This extension allows matching brackets to be identified with colours. The user can define which characters to match, and which colours to use.

It's make a code review more convenient, not only for PHP developers, so maybe it's better to write general netbeans plugin

**Comment by junichi11** [comment]
Hello,

Unfortunately, I'm not sure if we can implement that feature in a plugin at the moment... I won't implement it in this plugin even if it is possible. I would create a new plugin.

Maybe, you should report it to [JIRA](https://issues.apache.org/jira/projects/NETBEANS/issues) than here :)

Sorry, but I'll close this issue because it is not proper in this plugin.
Thanks.

**Comment by junichi11** [comment]
@vitaly-los Probably, It is possible in NetBeans. I'll create it as a new plugin if I can make time.
